### ISSUE TITLE
Total scores and criteria breakdown not to scale

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#100]
The length of the total score bars in the group chart should be the sum of the lengths of the per-criterion bars.

**Comment by ValueChart** [comment]
This issue is a result of the visual encodings we are using for Group ValueCharts. 

A user's weight outlines (the red rectangles) only span the entire height of an objective's row when that user has assigned the largest weight to that objective. Since an alternative's score for a given objective can only fill the weight outline, it is clear that a perfect score for an objective will not always span the entire height of that objective's row. 

Yet, we still expect the height of a perfect alternative (for a given user) in the stacked bar chart to be the height of the bar chart, not the combined height of the user's weight outlines. 

This is what creates the difference in heights between the breakdown component bars and the stacked bar chart component bars.

**Comment by aaronpmishkin** [comment]
See experimental branch for implementation. This will be merged into the main branch if the new encoding is approved.

Commit 805a1be implements scaling the SummaryChart to preserve utility unit length.

**Comment by aaronpmishkin** [comment]
Merged into main branch by 38c8bd3
