### ISSUE TITLE
Direct Imported ValueCharts to Create Workflow

### ISSUE THREAD

**Issue by aaronpmishkin** [ValueChart/WebValueCharts#157]

**Comment by MalakronikMausi** [comment]
As it stands, redirect to create with purpose EditChart will cause the previous chart to get overwritten even if the user supplies a new name (because it will have the same database ID). I don't think we need to read/write the ID anymore now that name uniqueness is ensured. 

Also, we cannot simply remove the nameChanged check - if the name hasn't been changed, the availability check will always fail since the name is taken by the current chart.  I now remember that is why I put it there in the first place.

Let's discuss this further before implementing anything.

**Comment by aaronpmishkin** [comment]
Resolved by 84a7babbcf2430ae15ace5b688ec9e1c793e4374.
