### ISSUE TITLE
Save alternative/objective order when "Save" is clicked

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#183]
If the chart owner reorders the alternatives or objectives in ValueChartViewer, clicking the "Save" button should write these changes. Right now, these changes only get written when they go back through the create workflow via "Edit Chart."

(I don't know if the current behavior is by design, but if we are going to save the reordering at all, we should do it consistently.)

**Comment by MalakronikMausi** [comment]
I cannot reproduce the scenario where the reordering was saved to the database by the create workflow. There must have been another difference that triggered the write. In any case, I think saving when "Save" is clicked makes the most sense.

**Comment by aaronpmishkin** [comment]
Why should we save these changes to the database? Changing the alternative or objective orders and then pushing those changes to other users is strange - why do the other users care how the owner has reordered their alternatives/objectives?

The current behavior is by design; I don't think that order information should be saved. Given this, it may be necessary to implement something that **prevents** order information from being saved to the database by accident in Create.

**Comment by aaronpmishkin** [comment]
### Post Meeting Update:

We decided that changes to the alternative/objective order by the chart owner should be sent to all users. Changes of this type by other users will not be propagated.

**Comment by aaronpmishkin** [comment]
Implemented by 6eeaad8.
