### ISSUE TITLE
Deactivate Save button for chart creator if neither structure nor preferences have changed

### ISSUE THREAD

**Issue by MalakronikMausi** [ValueChart/WebValueCharts#195]

**Comment by MalakronikMausi** [comment]
To do if you're interested.

**Comment by TylerJamesMalloy** [comment]
I believe that when the user presses the save button and nothing needs to be saved there is no notification that the chart saved. With this in mind I tried to find out how the save function determines wether or not the chart has any updates and I ended up in the Valuechart.http.ts file with a potential solution, but it turns out this method sends far to many http requests and slows down the chart considerably. I'm assuming there is another way but I'll have to look around to find out how.
